name: Create Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.2'

      - name: Generate Momentum Types
        run: python3 src/panorama_jsdoc_gen.py panorama-dumps/momentum/js_scopes_latest.txt panorama-dumps/momentum/events_latest.txt __types_momentum.js
        
      - name: Generate P2CE Types
        run: python3 src/panorama_jsdoc_gen.py panorama-dumps/p2ce/js_scopes_latest.txt panorama-dumps/p2ce/events_latest.txt __types_p2ce.js


      - name: Upload Momentum Artifact
        uses: actions/upload-artifact@v2
        with:
          name: MomentumTypes
          path: __types_momentum.js

      - name: Upload P2CE Artifact
        uses: actions/upload-artifact@v2
        with:
          name: P2CETypes
          path: __types_p2ce.js
      

      - name: Zip Momentum Typefile
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: __types_momentum.js
          filename: 'types_momentum.zip'
          
      - name: Zip P2CE Typefile
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: __types_p2ce.js
          filename: 'types_p2ce.zip'
          

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          files: |
            types_momentum.zip
            types_p2ce.zip
          fail_on_unmatched_files: true