name: Run CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.2'

      # Runs a single command using the runners shell
      - name: Run Script
        run: python3 panorama_jsdoc_gen.py dump_samples/momentum-feb-20-2022.txt __panorama_types.js
    
      - uses: actions/upload-artifact@v2
        with:
          name: PanoramaTypes
          path: __panorama_types.js
