name: Run CI

on:
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.2'

      - name: Generate Momentum Types
        run: python3 panorama_jsdoc_gen.py dumps/momentum_latest.txt __types_momentum.js
        
      - name: Generate P2CE Types
        run: python3 panorama_jsdoc_gen.py dumps/p2ce_latest.txt __types_p2ce.js
    
      - name: Upload Momentum Artifact
        uses: actions/upload-artifact@v2
        with:
          name: MomentumTypes
          path: __types_momentum.js

      - name: Upload P2CE Artifact
        uses: actions/upload-artifact@v2
        with:
          name: P2CETypes
          path: __types_p2ce.js